server:
  port: 8081

spring:
  application:
    name: agendador-tarefas

  data:
    mongodb:
      host: localhost
      port: 27017

jwt:
  expiration: 3600000

usuario:
  service:
    url: http://localhost:8080