server:
  port: 8081

spring:
  application:
    name: agendador-tarefas

  data:
    mongodb:
      host: localhost
      port: 27017

usuario:
  service:
    url: ${USUARIO_SERVICE_URL:http://localhost:8080}

tarefa:
  max-tentativas: 5