spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_agendador
      database: db_agendador     # força explicitamente

  # Linha de debug (vamos remover depois)
  config:
    import: optional:file:./debug.txt

jwt:
  secret: sua-chave-secreta-super-segura-que-deve-ser-bem-longa-aqui
  expiration: 3600000

usuario:
  service:
    url: http://localhost:8080

