server:
  port: 8081

spring:
  application:
    name: agendador-tarefas
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  secret: ${JWT_SECRET:minhaChaveSuperSecretaParaAssinar0Token1234567890}
  expiration: 3600000

usuario:
  service:
    url: ${USUARIO_SERVICE_URL:http://localhost:8080}